openapi: 3.0.0
info:
  title: Example OpenApi 3 spec
  description: Use to recreate a bug
  version: 0.1.0
paths:
  /recreate/bug/{id}:
    get:
      parameters:
          - in: path
            name: id
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  expectedProperty1:
                    type: string
